/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <hamsandwich>
#include <codmod>
#include <fun>
#include <colorchat>

new const perk_name[] = "Blademail";
new const perk_desc[] = "1 - LW seconds to reflect 100% Damage recieve";

new bool:ma_perk[33];
new wartosc_perku[33];
new bool:flag[33];	// Skill active flag
new bool:flag2[33];	// Skill used flag
new msg_bartime;

public plugin_init() 
{
	register_plugin(perk_name, "1.0", "MasamuneDate");
	cod_register_perk(perk_name, perk_desc, 1, 4);
	RegisterHam(Ham_TakeDamage, "player", "TakeDamage");
	register_event("ResetHUD", "ResetHUD", "abe");
	msg_bartime = get_user_msgid("BarTime");
}

public cod_perk_enabled(id, wartosc)
{
	ma_perk[id] = true;
	wartosc_perku[id] = wartosc;
	ResetHUD(id);
	ColorChat(id, GREEN, "Created by MasamuneDate", perk_name);
}

public cod_perk_disabled(id)
{
	ma_perk[id] = false;
	flag[id] = false;
	flag2[id] = true;
}

public cod_perk_used(id)
{
	if(!is_user_alive(id))
		return;
	
	if(flag2[id])
	{
		ColorChat(id, RED, "Ability Used !");
		return;
	}
	
	flag[id] = true;
	set_task(float(wartosc_perku[id]), "off", id);	// Duration, Func Name, ID
	message_begin(MSG_ONE, msg_bartime, _, id);
	write_short(wartosc_perku[id]);
	message_end();
}

public off(id)
{
	flag[id] = false;
}

public TakeDamage(this, idinflictor, idattacker, Float:damage, damagebits, id)
{
	if(!is_user_connected(idattacker))
		return HAM_IGNORED;
		
	if(!ma_perk[idattacker])
		return HAM_IGNORED;
	
	if(flag[id] != false)
		cod_inflict_damage(this, idattacker, damage, 0.0, idinflictor, damagebits);
	return HAM_SUPERCEDE;
}

public ResetHUD(id)
{
	flag2[id] = false;
}
/* AMXX-Studio Notes - DO NOT MODIFY BELOW HERE
*{\\ rtf1\\ ansi\\ deff0{\\ fonttbl{\\ f0\\ fnil Tahoma;}}\n\\ viewkind4\\ uc1\\ pard\\ lang1045\\ f0\\ fs16 \n\\ par }
*/
